#!/usr/bin/env bash

set -euo pipefail

user=

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            printf 'Usage: gh clone-all <user|org>\n'
            printf '       gh clone-all https://github.com/<user|org>\n'
            exit 0
            ;;
        *)
            user="$1"
            ;;
    esac

    shift
done

if [[ -z "$user" ]]; then
    printf '%s: missing <user|org>\n' "$0" 1>&2
    exit 1
fi

get_repos() {
    local owner="$1"

    gh api graphql --paginate -q '.data.repositoryOwner.repositories.nodes[] | .nameWithOwner' -F owner="$owner" -f query='
        query($owner: String! $endCursor: String) {
            repositoryOwner(login: $owner) {
                repositories(first: 100 ownerAffiliations: OWNER isFork: false orderBy: { field: NAME direction: ASC} after: $endCursor) {
                    totalCount pageInfo { hasNextPage endCursor } nodes { nameWithOwner }
                }
            }
        }
    '
}

get_repos "${user#https://github.com/}" | head -2 | xargs -r -I '{}' -- sh -c '
    if [[ ! -d "$( basename "{}" )" ]]; then
        gh repo clone "{}"
    fi
'
