#!/usr/bin/env bash

set -euo pipefail

fork='false'
user=

while [[ $# -gt 0 ]]; do
    case "$1" in
        -f|--fork)
            fork='true'
            ;;
        -h|--help)
            printf 'Usage: gh clone-all [-f | --fork] <user|org>\n'
            printf '       gh clone-all [-f | --fork] https://github.com/<user|org>\n'
            exit 0
            ;;
        *)
            user="$1"
            ;;
    esac

    shift
done

if [[ -z "$user" ]]; then
    printf '%s: missing <user|org>\n' "$0" 1>&2
    exit 1
fi

get_repos() {
    local owner="$1"

    # shellcheck disable=SC2016 # Expressions don't expand in single quotes, use double quotes for that.
    gh api graphql --paginate -q '.data.repositoryOwner.repositories.nodes[] | .nameWithOwner' -F owner="$owner" -F isFork="$fork" -f query='
        query($owner: String! $isFork: Boolean $endCursor: String) {
            repositoryOwner(login: $owner) {
                repositories(first: 100 ownerAffiliations: OWNER isFork: $isFork orderBy: { field: NAME direction: ASC} after: $endCursor) {
                    totalCount pageInfo { hasNextPage endCursor } nodes { nameWithOwner }
                }
            }
        }
    '
}

# shellcheck disable=SC2016 # Expressions don't expand in single quotes, use double quotes for that.
get_repos "${user#https://github.com/}" | xargs -r -I '{}' -- sh -c '
    if [[ ! -d "$( basename "{}" )" ]]; then
        gh repo clone "{}"
    fi
'
