#!/bin/bash

set -euo pipefail

user=
jobs=1
verbose=

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            printf 'Usage: gh clone-all <user>\n'
            printf '       gh clone-all https://github.com/<user>\n'
            exit 0
            ;;
        -j|--jobs)
            jobs="$2"
            shift
            ;;
        -j*)
            jobs="${1#-j}"
            ;;
        --jobs=*)
            jobs="${1#--jobs=}"
            ;;
        -v|--verbose)
            verbose=1
            ;;
        *)
            user="$1"
            ;;
    esac

    shift
done

gh repo list "$user" --json url --limit 1000 --jq '.[] | .url' |
    parallel -j"$jobs" 'if [[ -n "'"$verbose"'" ]]; then echo {}; fi; gh get {}'
